project:
  type: website
  output-dir: docs

website:
  title: "Ece's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU660 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/ecavusgil
      - icon: linkedin
        href: https://www.linkedin.com/in/ece-%C3%A7avu%C5%9Fgil-91304218a/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU660 - Spring 2025" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: lux
    light: simplex 
    dark: cyborg
    linkcolor: "#9370DB"
    #fontcolor: ""
    fontsize: 0.5 em
    css: styles.css
    df_print: paged
    
  pdf:
     pdf-engine: pdflatex

editor: visual



